# Generated by Django 5.2.1 on 2025-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='advert/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='founder/')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('TOSHKENT', 'Toshkent'), ('SIRDARYO', 'Sirdaryo'), ('SAMARQAND', 'Samarqand'), ('ANDIJON', 'Andijon'), ('FARGONA', 'Fargona'), ('JIZZAX', 'Jizzax'), ('NAVOIY', 'Navoiy'), ('SURXONDARYO', 'Surxondaryo'), ('QASHQADARYO', 'Qashqadaryo'), ('XORAZM', 'Xorazm'), ('QORAQALPOGISTON', 'Qoraqalpogiston'), ('BUXORO', 'Buxoro'), ('NAMANGAN', 'Namangan')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='listings/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('bedrooms_num', models.IntegerField(max_length=99)),
                ('bathrooms_num', models.IntegerField(max_length=99)),
                ('garage_num', models.IntegerField(max_length=99)),
                ('area_size', models.IntegerField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
            ],
        ),
    ]
