# Generated by Django 5.2.1 on 2025-05-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage_num',
            field=models.IntegerField(),
        ),
    ]
