# Generated by Django 5.2.1 on 2025-05-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0002_alter_listing_area_size_alter_listing_bathrooms_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HOVLI', 'Hovli'), ('KOTTEJ', 'Kottej'), ('TOMORQA', 'Tomorqa'), ('KVARTIRA', 'KVARTIRA')], max_length=100),
        ),
    ]
