# Generated by Django 5.2.1 on 2025-05-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HOVLI', 'Hovli'), ('KOTTEJ', 'Kottej'), ('TOMORQA', 'Tomorqa'), ('KVARTIRA', 'Kvartira')], max_length=100),
        ),
    ]
