# Generated by Django 5.2.1 on 2025-05-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
