# Generated by Django 5.2.1 on 2025-05-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0006_listing_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
