# Generated by Django 5.2.1 on 2025-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postadvert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadvert',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
